import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { Pressable, StyleSheet, View } from 'react-native';
import { AppText } from '@/components/common/app-text';
import { colors, layout, radius, spacing } from '@/design/tokens';
import { ProgressFeedback } from '@/types/progress';
import { ProgressCard } from './progress-card';
export function FeedbackTimeline({ feedback, onFeedbackPress }: { feedback: ProgressFeedback[]; onFeedbackPress: (feedback: ProgressFeedback) => void }) {
  return <ProgressCard><View style={styles.heading}><View style={styles.headingCopy}><AppText variant="heading" weight="bold">Coach Feedback</AppText><AppText variant="bodySmall" color={colors.neutral.textSecondary}>Recent development guidance</AppText></View><MaterialCommunityIcons name="message-text-outline" size={22} color={colors.brand.blue} /></View><View style={styles.timeline}>{feedback.map((entry, index) => <View key={entry.id} style={styles.entry}><View style={styles.rail}><View style={[styles.dot, index === 0 && styles.activeDot]} />{index < feedback.length - 1 ? <View style={styles.line} /> : null}</View><Pressable testID={`progress-feedback-${entry.id}`} onPress={() => onFeedbackPress(entry)} accessibilityRole="button" accessibilityLabel={`Feedback from Coach ${entry.coachName}, ${entry.date}. Open details.`} style={({ pressed }) => [styles.entryContent, index === 0 && styles.activeEntry, pressed && styles.pressed]}><View style={styles.entryMeta}><AppText variant="bodySmall" weight="bold">Coach {entry.coachName}</AppText><AppText variant="caption" weight="medium" color={colors.neutral.textSecondary}>{entry.date}</AppText></View><AppText variant="bodySmall" color={colors.neutral.textSecondary} numberOfLines={2}>{entry.message}</AppText><View style={styles.focus}><MaterialCommunityIcons name="target" size={15} color={colors.brand.blue} /><AppText variant="caption" weight="bold" color={colors.brand.blue} numberOfLines={1}>Focus: {entry.focus}</AppText><MaterialCommunityIcons name="chevron-right" size={17} color={colors.brand.blue} /></View></Pressable></View>)}</View></ProgressCard>;
}
const styles = StyleSheet.create({ heading: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: spacing.sm }, headingCopy: { flex: 1, minWidth: 0 }, timeline: { marginTop: spacing.sm }, entry: { flexDirection: 'row', gap: spacing.sm }, rail: { width: 16, alignItems: 'center' }, dot: { width: 10, height: 10, borderRadius: radius.pill, backgroundColor: colors.neutral.borderStrong, marginTop: spacing.xs }, activeDot: { backgroundColor: colors.brand.blue, borderWidth: 3, borderColor: colors.brand.blueSoft, width: 14, height: 14 }, line: { width: 1, flex: 1, minHeight: 58, backgroundColor: colors.neutral.border, marginVertical: spacing.xs }, entryContent: { flex: 1, minWidth: 0, minHeight: layout.minTouchTarget, paddingBottom: spacing.sm, gap: spacing.xs, borderRadius: radius.medium }, activeEntry: { padding: spacing.sm, marginBottom: spacing.sm, paddingBottom: spacing.sm, backgroundColor: colors.brand.blueSoft }, entryMeta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm }, focus: { minHeight: 28, flexDirection: 'row', alignItems: 'center', gap: spacing.xs }, pressed: { opacity: 0.72 } });
