import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { StyleSheet, View } from 'react-native';
import Svg, { Circle, Line, Polygon, Text as SvgText } from 'react-native-svg';
import { AnimatedPressable } from '@/components/common/animated-pressable';
import { AppText } from '@/components/common/app-text';
import { ProgressBar } from '@/components/common/progress-bar';
import { colors, fontFamilies, radius, spacing } from '@/design/tokens';
import { SkillRating } from '@/types/progress';
import { ProgressCard } from './progress-card';

function RatingRow({ skill, onPress }: { skill: SkillRating; onPress: () => void }) {
  return <AnimatedPressable testID={`progress-skill-${skill.key}`} onPress={onPress} accessibilityRole="button" accessibilityLabel={`${skill.label}, ${skill.rating.toFixed(1)} out of 5. Open assessment.`} style={styles.ratingRow}><View style={styles.ratingTop}><AppText variant="bodySmall" weight="bold" style={styles.skillLabel}>{skill.label}</AppText><View style={styles.ratingValue}><AppText variant="body" weight="extraBold">{skill.rating.toFixed(1)}</AppText><AppText variant="caption" weight="bold" color={colors.neutral.textSecondary}>/5</AppText><MaterialCommunityIcons name="arrow-up" size={13} color={colors.status.success} /><AppText variant="caption" weight="bold" color={colors.status.success}>{skill.change.toFixed(1)}</AppText></View></View><ProgressBar progress={skill.rating / 5} trackStyle={styles.track} accessibilityLabel={`${skill.label} ${skill.rating.toFixed(1)} out of 5`} /></AnimatedPressable>;
}
export function CoachSkillRatingsCard({ ratings, onSkillPress }: { ratings: SkillRating[]; onSkillPress: (skill: SkillRating) => void }) {
  return <ProgressCard><View style={styles.cardHeading}><View><AppText variant="heading" weight="bold">Coach Skill Ratings</AppText><AppText variant="bodySmall" color={colors.neutral.textSecondary}>Latest technical review · out of 5</AppText></View><View style={styles.coachIcon}><MaterialCommunityIcons name="account-tie" size={20} color={colors.brand.navy} /></View></View><View style={styles.ratings}>{ratings.map((skill) => <RatingRow key={skill.key} skill={skill} onPress={() => onSkillPress(skill)} />)}</View></ProgressCard>;
}
function polarPoint(index: number, radiusValue: number, total: number, centerX: number, centerY: number): [number, number] { const angle = -Math.PI / 2 + (index * Math.PI * 2) / total; return [centerX + Math.cos(angle) * radiusValue, centerY + Math.sin(angle) * radiusValue]; }
function pointString(points: [number, number][]): string { return points.map(([x, y]) => `${x},${y}`).join(' '); }
export function SkillRadarCard({ ratings }: { ratings: SkillRating[] }) {
  const centerX = 150; const centerY = 110; const chartRadius = 70; const labelRadius = 98; const gridLevels = [0.25, 0.5, 0.75, 1];
  const dataPoints = ratings.map((skill, index) => polarPoint(index, chartRadius * (skill.rating / 5), ratings.length, centerX, centerY));
  return <ProgressCard accessibilityLabel={`Skill balance chart. ${ratings.map((skill) => `${skill.label} ${skill.rating} out of 5`).join(', ')}`}><AppText variant="heading" weight="bold">Skill Balance</AppText><AppText variant="bodySmall" color={colors.neutral.textSecondary}>Current balance across five football skills</AppText><View style={styles.radarWrap}><Svg width="100%" height={172} viewBox="0 0 300 220">{gridLevels.map((level) => <Polygon key={level} points={pointString(ratings.map((_, index) => polarPoint(index, chartRadius * level, ratings.length, centerX, centerY)))} fill="none" stroke={colors.neutral.borderStrong} strokeWidth={1} />)}{ratings.map((_, index) => { const [x, y] = polarPoint(index, chartRadius, ratings.length, centerX, centerY); return <Line key={index} x1={centerX} y1={centerY} x2={x} y2={y} stroke={colors.neutral.borderStrong} strokeWidth={1} />; })}<Polygon points={pointString(dataPoints)} fill={colors.status.infoSoft} fillOpacity={0.8} stroke={colors.brand.blue} strokeWidth={2.5} />{dataPoints.map(([x, y], index) => <Circle key={ratings[index].key} cx={x} cy={y} r={3.5} fill={colors.neutral.white} stroke={colors.brand.blue} strokeWidth={2} />)}{ratings.map((skill, index) => { const [x, y] = polarPoint(index, labelRadius, ratings.length, centerX, centerY); return <SvgText key={skill.key} x={x} y={y} fill={colors.neutral.textSecondary} fontFamily={fontFamilies.semibold} fontSize={11} textAnchor="middle" alignmentBaseline="middle">{skill.label}</SvgText>; })}</Svg></View><View style={styles.radarNote}><MaterialCommunityIcons name="lightbulb-on-outline" size={18} color={colors.status.warning} /><AppText variant="bodySmall" color={colors.neutral.textSecondary} style={styles.skillLabel}><AppText variant="bodySmall" weight="bold">Next focus:</AppText> game awareness and weak-foot passing.</AppText></View></ProgressCard>;
}
const styles = StyleSheet.create({ cardHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm }, coachIcon: { width: 40, height: 40, borderRadius: radius.medium, backgroundColor: colors.brand.blueSoft, alignItems: 'center', justifyContent: 'center' }, ratings: { marginTop: spacing.md, gap: spacing.xs }, ratingRow: { minHeight: 48, justifyContent: 'center', gap: spacing.xs, borderRadius: radius.small }, ratingTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm }, skillLabel: { flex: 1, minWidth: 0 }, ratingValue: { flexDirection: 'row', alignItems: 'baseline', gap: spacing.xs }, track: { height: 7, borderRadius: radius.pill, backgroundColor: colors.neutral.divider, overflow: 'hidden' }, fill: { height: '100%', borderRadius: radius.pill, backgroundColor: colors.brand.blue }, radarWrap: { marginTop: spacing.sm, alignItems: 'center' }, radarNote: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, padding: spacing.sm, borderRadius: radius.medium, backgroundColor: colors.status.warningSoft } });
