import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { StyleSheet, useWindowDimensions, View } from 'react-native';

import { AnimatedPressable } from '@/components/common/animated-pressable';
import { AppText } from '@/components/common/app-text';
import { ProgressBar } from '@/components/common/progress-bar';
import { colors, layout, radius, shadows, spacing } from '@/design/tokens';
import { LearningLesson, LessonProgress } from '@/types/learning';
import { LessonThumbnail } from './lesson-thumbnail';

const DurationBadge = ({ minutes }: { minutes: number }) => <View style={styles.duration}><MaterialCommunityIcons name="clock-outline" size={13} color={colors.neutral.white} /><AppText variant="caption" weight="bold" color={colors.neutral.white}>{minutes} min</AppText></View>;
const meta = (lesson: LearningLesson) => `${lesson.category} · Coach ${lesson.coachName}`;

export function ContinueWatchingCard({ lesson, progress, onPress }: { lesson: LearningLesson; progress: LessonProgress; onPress: () => void }) {
  const percent = progress.watchedMinutes / lesson.durationMinutes;
  return <AnimatedPressable testID="learn-continue-watching" onPress={onPress} accessibilityRole="button" accessibilityLabel={`Continue ${lesson.title}, ${progress.watchedMinutes} of ${lesson.durationMinutes} minutes watched`} style={styles.featureCard}><View><LessonThumbnail thumbnail={lesson.thumbnail} showPlay style={styles.featureImage} /><View style={styles.durationPosition}><DurationBadge minutes={lesson.durationMinutes} /></View></View><View style={styles.featureBody}><AppText variant="caption" weight="extraBold" color={colors.brand.blue}>{lesson.category.toUpperCase()}</AppText><AppText variant="heading" weight="extraBold" numberOfLines={2}>{lesson.title}</AppText><AppText variant="bodySmall" color={colors.neutral.textSecondary} numberOfLines={1}>Coach {lesson.coachName}</AppText><View style={styles.progressLabels}><AppText variant="caption" weight="semibold">Your progress</AppText><AppText variant="caption" color={colors.neutral.textSecondary}>{progress.watchedMinutes} / {lesson.durationMinutes} min</AppText></View><ProgressBar progress={percent} /><View style={styles.continueAction}><AppText variant="bodySmall" weight="bold" color={colors.neutral.white}>Continue</AppText></View></View></AnimatedPressable>;
}

export function RecommendedLessonCard({ lesson, onPress }: { lesson: LearningLesson; onPress: () => void }) {
  const { width } = useWindowDimensions();
  const cardWidth = Math.min(276, width - layout.compactScreenPadding * 2 - spacing.md);
  return <AnimatedPressable testID={`learn-lesson-${lesson.id}`} onPress={onPress} accessibilityRole="button" accessibilityLabel={`Recommended lesson ${lesson.title}`} style={[styles.recommended, { width: cardWidth }]}><View><LessonThumbnail thumbnail={lesson.thumbnail} style={styles.recommendedImage} /><View style={styles.recommendedBadge}><MaterialCommunityIcons name="star-four-points" size={12} color={colors.brand.navy} /><AppText variant="caption" weight="extraBold" color={colors.brand.navy}>RECOMMENDED</AppText></View><View style={styles.durationPosition}><DurationBadge minutes={lesson.durationMinutes} /></View></View><View style={styles.recommendedBody}><AppText variant="heading" weight="extraBold" numberOfLines={2}>{lesson.title}</AppText><AppText variant="bodySmall" color={colors.neutral.textSecondary} numberOfLines={1}>{meta(lesson)}</AppText><View style={styles.ageRow}><MaterialCommunityIcons name="account-group-outline" size={16} color={colors.brand.blue} /><AppText variant="caption" weight="semibold" color={colors.neutral.textSecondary}>{lesson.suitableCategories.join(' · ')}</AppText></View></View></AnimatedPressable>;
}

export function LessonCard({ lesson, progress, onPress }: { lesson: LearningLesson; progress: LessonProgress; onPress: () => void }) {
  return <AnimatedPressable testID={`learn-lesson-${lesson.id}`} onPress={onPress} accessibilityRole="button" accessibilityLabel={`${lesson.title}, ${progress.status.replace('-', ' ')}`} style={styles.lesson}><View style={styles.lessonMedia}><LessonThumbnail thumbnail={lesson.thumbnail} style={styles.lessonImage} /><View style={styles.durationPosition}><DurationBadge minutes={lesson.durationMinutes} /></View></View><View style={styles.lessonCopy}><View style={styles.categoryRow}><AppText variant="caption" weight="extraBold" color={colors.brand.blue}>{lesson.category.toUpperCase()}</AppText>{progress.status === 'completed' && <AppText variant="caption" weight="bold" color={colors.status.success}>COMPLETED</AppText>}</View><AppText variant="heading" weight="extraBold" numberOfLines={2}>{lesson.title}</AppText><AppText variant="bodySmall" color={colors.neutral.textSecondary} numberOfLines={1}>Coach {lesson.coachName} · {lesson.suitableCategories.join(', ')}</AppText>{progress.status === 'in-progress' && <ProgressBar progress={progress.watchedMinutes / lesson.durationMinutes} />}</View><MaterialCommunityIcons name="chevron-right" size={22} color={colors.neutral.textMuted} /></AnimatedPressable>;
}

export function CompletedLessonCard({ lesson, progress, onPress }: { lesson: LearningLesson; progress: LessonProgress; onPress: () => void }) {
  return <AnimatedPressable testID={`learn-lesson-${lesson.id}`} onPress={onPress} accessibilityRole="button" accessibilityLabel={`${lesson.title}, completed ${progress.completedDate ?? ''}`} style={styles.completed}><LessonThumbnail thumbnail={lesson.thumbnail} style={styles.completedImage} /><View style={styles.completedCopy}><AppText variant="bodySmall" weight="bold" numberOfLines={2}>{lesson.title}</AppText><View style={styles.completeMeta}><MaterialCommunityIcons name="check-circle" size={16} color={colors.status.success} /><AppText variant="caption" color={colors.neutral.textSecondary}>Completed {progress.completedDate}</AppText></View></View><MaterialCommunityIcons name="chevron-right" size={21} color={colors.neutral.textMuted} /></AnimatedPressable>;
}

const styles = StyleSheet.create({
  featureCard: { ...shadows.card, overflow: 'hidden', borderRadius: radius.large, borderWidth: 1, borderColor: colors.neutral.border, backgroundColor: colors.neutral.surface }, featureImage: { width: '100%', aspectRatio: layout.learningImageAspectRatio }, featureBody: { padding: layout.cardPadding, gap: spacing.xs }, durationPosition: { position: 'absolute', top: spacing.sm, right: spacing.sm }, duration: { minHeight: 28, paddingHorizontal: spacing.xs, borderRadius: radius.pill, flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: colors.mediaBadge }, progressLabels: { marginTop: spacing.xs, flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm }, track: { height: 6, borderRadius: radius.pill, backgroundColor: colors.neutral.divider, overflow: 'hidden' }, fill: { height: '100%', borderRadius: radius.pill, backgroundColor: colors.brand.blue }, continueAction: { minHeight: layout.buttonHeight, paddingHorizontal: spacing.lg, alignItems: 'center', justifyContent: 'center', borderRadius: radius.medium, backgroundColor: colors.brand.navy },
  recommended: { ...shadows.card, overflow: 'hidden', borderRadius: radius.large, borderWidth: 1, borderColor: colors.neutral.border, backgroundColor: colors.neutral.surface }, recommendedImage: { width: '100%', aspectRatio: 1.82 }, recommendedBadge: { position: 'absolute', top: spacing.sm, left: spacing.sm, minHeight: 28, paddingHorizontal: spacing.xs, borderRadius: radius.pill, flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: colors.brand.goldSoft }, recommendedBody: { height: 106, paddingVertical: layout.compactRowPaddingVertical, paddingHorizontal: layout.compactRowPaddingHorizontal, gap: spacing.xs }, ageRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  lesson: { ...shadows.card, minHeight: 108, padding: spacing.sm, borderRadius: radius.large, borderWidth: 1, borderColor: colors.neutral.border, backgroundColor: colors.neutral.surface, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, lessonMedia: { width: 104 }, lessonImage: { width: '100%', aspectRatio: 1.35 }, lessonCopy: { flex: 1, minWidth: 0, gap: spacing.xs }, categoryRow: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.xs },
  completed: { minHeight: 76, paddingVertical: layout.compactRowPaddingVertical, paddingHorizontal: layout.compactRowPaddingHorizontal, borderRadius: radius.compact, borderWidth: 1, borderColor: colors.neutral.border, backgroundColor: colors.neutral.surface, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, completedImage: { width: 72, height: 52, borderRadius: radius.small }, completedCopy: { flex: 1, minWidth: 0, gap: spacing.xs }, completeMeta: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs }, pressed: { opacity: 0.82, transform: [{ scale: 0.985 }] },
});
