import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { Pressable, StyleSheet, View } from 'react-native';
import { AppText } from '@/components/common/app-text';
import { StatusBadge } from '@/components/common/status-badge';
import { CoachFeedback } from '@/types/player';
import { colors, layout, radius, shadows, spacing } from '@/design/tokens';
export function CoachFeedbackCard({ feedback, onPress }: { feedback: CoachFeedback; onPress: () => void }) {
  return <View style={styles.card}><View style={styles.header}><View style={styles.avatar}><MaterialCommunityIcons name="account-tie" size={24} color={colors.brand.navy} /></View><View style={styles.identity}><AppText variant="heading" weight="bold">Coach {feedback.coachName}</AppText><AppText variant="bodySmall" weight="medium" color={colors.neutral.textSecondary}>{feedback.coachRole} · {feedback.date}</AppText></View><StatusBadge label="New" /></View><AppText color={colors.neutral.textSecondary} numberOfLines={4} style={styles.feedback}>{feedback.text}</AppText><View style={styles.focus}><View style={styles.focusIcon}><MaterialCommunityIcons name="target" size={18} color={colors.brand.blue} /></View><View style={styles.identity}><AppText variant="caption" weight="bold" color={colors.neutral.textSecondary}>CURRENT FOCUS</AppText><AppText variant="bodySmall" weight="bold">{feedback.focus}</AppText></View><Pressable testID="home-view-report" onPress={onPress} accessibilityRole="button" accessibilityLabel="View coach report" hitSlop={4} style={({ pressed }) => [styles.reportAction, pressed && styles.pressed]}><AppText variant="bodySmall" weight="bold" color={colors.brand.blue}>View report</AppText><MaterialCommunityIcons name="chevron-right" size={17} color={colors.brand.blue} /></Pressable></View></View>;
}
const styles = StyleSheet.create({ card: { ...shadows.card, backgroundColor: colors.neutral.surface, borderWidth: 1, borderColor: colors.neutral.border, borderRadius: radius.large, padding: layout.cardPadding, gap: spacing.sm }, header: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, avatar: { width: 46, height: 46, borderRadius: radius.medium, backgroundColor: colors.brand.blueSoft, alignItems: 'center', justifyContent: 'center' }, identity: { flex: 1, minWidth: 0 }, feedback: { lineHeight: 22 }, focus: { minHeight: 60, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, backgroundColor: colors.brand.blueSoft, borderRadius: radius.medium, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs }, focusIcon: { width: layout.compactIconSize, height: layout.compactIconSize, borderRadius: radius.small, backgroundColor: colors.neutral.white, alignItems: 'center', justifyContent: 'center' }, reportAction: { minHeight: layout.minTouchTarget, flexDirection: 'row', alignItems: 'center', gap: spacing.xs }, pressed: { opacity: 0.68, transform: [{ scale: 0.98 }] } });
