import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { Image } from 'expo-image';
import { useState } from 'react';
import { StyleSheet, View } from 'react-native';
import { AppButton } from '@/components/common/app-button';
import { AppText } from '@/components/common/app-text';
import { ProgressBar } from '@/components/common/progress-bar';
import { colors, layout, radius, shadows, spacing } from '@/design/tokens';
import { LearningVideo } from '@/types/player';
import { clampProgress, formatVideoProgress } from '@/utils/format';
export function LearningVideoCard({ video, onPress }: { video: LearningVideo; onPress: () => void }) {
  const percent = clampProgress((video.watchedMinutes / video.durationMinutes) * 100);
  const [useFallback, setUseFallback] = useState(false);
  const thumbnail = useFallback ? require('@/assets/images/home/training-hero.png') : require('@/assets/images/home/ball-control.png');
  return <View style={styles.card}><View style={styles.thumbnail}><Image source={thumbnail} onError={() => setUseFallback(true)} style={StyleSheet.absoluteFill} contentFit="cover" contentPosition="center" transition={180} accessibilityLabel="Football ball-control training demonstration" /><View style={styles.imageShade} /><View style={styles.play}><MaterialCommunityIcons name="play" size={26} color={colors.neutral.white} /></View><View style={styles.duration}><MaterialCommunityIcons name="clock-outline" size={13} color={colors.neutral.white} /><AppText variant="caption" weight="bold" color={colors.neutral.white}>{video.durationMinutes} min</AppText></View></View><View style={styles.content}><View style={styles.meta}><View style={styles.category}><AppText variant="caption" weight="extraBold" color={colors.brand.blue}>{video.type.toUpperCase()}</AppText></View><View style={styles.coach}><MaterialCommunityIcons name="account-outline" size={15} color={colors.neutral.textSecondary} /><AppText variant="bodySmall" weight="medium" color={colors.neutral.textSecondary}>Coach {video.coachName}</AppText></View></View><AppText variant="heading" weight="extraBold">{video.title}</AppText><View style={styles.progressHeader}><AppText variant="bodySmall" weight="medium" color={colors.neutral.textSecondary}>Session progress</AppText><AppText variant="bodySmall" weight="bold" color={colors.neutral.textSecondary}>{formatVideoProgress(video.watchedMinutes, video.durationMinutes)}</AppText></View><ProgressBar progress={percent / 100} trackStyle={styles.track} accessibilityLabel={`${percent} percent of ${video.title} watched`} /><AppButton testID="home-continue-lesson" label="Watch Session" onPress={onPress} accessibilityLabel={`Watch ${video.title}`} /></View></View>;
}
const styles = StyleSheet.create({ card: { ...shadows.card, backgroundColor: colors.neutral.surface, borderWidth: 1, borderColor: colors.neutral.border, borderRadius: radius.large, overflow: 'hidden' }, thumbnail: { aspectRatio: layout.learningImageAspectRatio, backgroundColor: colors.brand.navy, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }, imageShade: { ...StyleSheet.absoluteFillObject, backgroundColor: colors.mediaOverlay }, play: { width: 46, height: 46, borderRadius: radius.pill, backgroundColor: colors.mediaControl, borderWidth: 2, borderColor: colors.neutral.white, alignItems: 'center', justifyContent: 'center' }, duration: { position: 'absolute', right: spacing.md, top: spacing.md, minHeight: 28, borderRadius: radius.pill, backgroundColor: colors.mediaBadge, paddingHorizontal: spacing.sm, flexDirection: 'row', alignItems: 'center', gap: spacing.xs }, content: { padding: layout.cardPadding, gap: spacing.xs }, meta: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', columnGap: spacing.md, rowGap: spacing.xs }, category: { borderRadius: radius.pill, backgroundColor: colors.brand.blueSoft, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs }, coach: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs }, progressHeader: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm, marginTop: spacing.xs }, track: { height: 7, backgroundColor: colors.neutral.border, marginBottom: spacing.xs } });
