export const demoConfig = {
  storageVersion: 1,
  resetEnabled: __DEV__,
  academy: {
    primaryTrainingGround: 'GCC Football Ground',
  },
  timeline: {
    currentDateIso: '2026-07-11',
    currentDateLabel: 'Saturday, 11 July 2026',
    currentDateShort: 'Saturday, 11 July',
    currentSessionTime: '4:30 PM–6:00 PM',
    currentSessionStart: '16:30',
    currentSessionEnd: '18:00',
    currentSessionCountdown: 'Starts in 3 hours',
    latestAssessmentDate: '7 July 2026',
  },
  credentials: {
    player: { id: 'GCC-U13-024', password: 'demo123' },
    coach: { id: 'GCC-COACH-001', password: 'coach123' },
  },
  player: {
    name: 'Ayaan Mohammed',
    playerId: 'GCC-U13-024',
    category: 'U13 Development Squad',
    jerseyNumber: 10,
    headCoach: 'Sandeep',
    attendancePercent: 94,
    coachRating: 4.3,
    currentGoal: 'Weak-foot Passing',
    feeAmount: 1200,
    feeAmountDisplay: '₹1,200',
    feeDueDate: '15 July 2026',
    feeDueDateShort: '15 July',
  },
} as const;
