import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { StyleSheet, View } from 'react-native';

import { AnimatedPressable } from '@/components/common/animated-pressable';
import { AppText } from '@/components/common/app-text';
import { colors, layout, radius, spacing } from '@/design/tokens';
import { AcademyCommunicationUpdate, UpdateDateGroup } from '@/types/updates';
import { priorityUI, updateCategoryUI } from './update-category';

export function ImportantUpdateCard({ update, onPress }: { update: AcademyCommunicationUpdate; onPress: () => void }) {
  const priority = update.priority === 'normal' ? undefined : priorityUI[update.priority];
  return <AnimatedPressable testID={`update-important-${update.id}`} onPress={onPress} accessibilityRole="button" accessibilityLabel={`${priority?.label ?? 'Important'} update. ${update.title}. View details.`} style={styles.important}><View style={styles.importantIcon}><MaterialCommunityIcons name="alert-outline" size={23} color={colors.status.warning} /></View><View style={styles.copy}><View style={styles.priorityRow}>{priority && <AppText variant="caption" weight="extraBold" color={priority.color}>{priority.label}</AppText>}<AppText variant="caption" color={colors.neutral.textSecondary}>{update.relativeTime} · For {update.audienceLabel} · By {update.senderName}</AppText></View><AppText variant="heading" weight="extraBold" numberOfLines={2}>{update.title}</AppText><AppText variant="bodySmall" color={colors.neutral.textSecondary} numberOfLines={2}>{update.preview}</AppText><AppText variant="bodySmall" weight="bold" color={colors.brand.blue}>View details</AppText></View><View style={styles.arrow}><MaterialCommunityIcons name="chevron-right" size={21} color={colors.brand.blue} /></View></AnimatedPressable>;
}

export function UpdateListItem({ update, isRead, onPress }: { update: AcademyCommunicationUpdate; isRead: boolean; onPress: () => void }) {
  const category = updateCategoryUI[update.category];
  const priority = update.priority === 'normal' ? undefined : priorityUI[update.priority];
  return <AnimatedPressable testID={`update-item-${update.id}`} onPress={onPress} accessibilityRole="button" accessibilityLabel={`${isRead ? 'Read' : 'Unread'} ${update.category} update. ${update.title}${priority ? `. ${priority.label}` : ''}`} style={[styles.item, !isRead && styles.unread]}><View style={[styles.icon, { backgroundColor: category.surface }]}><MaterialCommunityIcons name={category.icon} size={21} color={category.color} /></View><View style={styles.copy}><View style={styles.categoryRow}><AppText variant="caption" weight="extraBold" color={category.color}>{update.category.toUpperCase()}</AppText>{!isRead && <View style={styles.unreadLabel}><AppText variant="caption" weight="extraBold" color={colors.brand.blue}>NEW</AppText></View>}{priority && <AppText variant="caption" weight="extraBold" color={priority.color}>{priority.label}</AppText>}</View><AppText variant="bodySmall" weight={isRead ? 'semibold' : 'extraBold'} numberOfLines={2}>{update.title}</AppText><AppText variant="bodySmall" color={colors.neutral.textSecondary} numberOfLines={2}>{update.preview}</AppText><AppText variant="caption" weight="semibold" color={colors.neutral.textSecondary}>{update.relativeTime} · For {update.audienceLabel} · By {update.senderName}</AppText></View><View style={styles.arrow}><MaterialCommunityIcons name="chevron-right" size={21} color={colors.neutral.textMuted} /></View></AnimatedPressable>;
}

export function UpdateSection({ title, updates, isRead, onOpen }: { title: UpdateDateGroup; updates: readonly AcademyCommunicationUpdate[]; isRead: (id: string) => boolean; onOpen: (id: string) => void }) {
  if (!updates.length) return null;
  return <View style={styles.section}><AppText variant="heading" weight="bold">{title}</AppText><View style={styles.list}>{updates.map((update) => <UpdateListItem key={update.id} update={update} isRead={isRead(update.id)} onPress={() => onOpen(update.id)} />)}</View></View>;
}

const styles = StyleSheet.create({ important: { minHeight: 112, paddingVertical: layout.compactRowPaddingVertical, paddingHorizontal: layout.compactRowPaddingHorizontal, borderRadius: radius.large, borderWidth: 1, borderColor: colors.amberBorder, backgroundColor: colors.status.warningSoft, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, importantIcon: { width: layout.standardIconSize, height: layout.standardIconSize, borderRadius: radius.medium, backgroundColor: colors.neutral.white, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1, minWidth: 0, gap: spacing.xs }, priorityRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, arrow: { width: layout.minTouchTarget, height: layout.minTouchTarget, alignItems: 'center', justifyContent: 'center' }, section: { gap: layout.sectionHeaderToCard }, list: { gap: layout.cardGap }, item: { minHeight: 108, paddingVertical: layout.compactRowPaddingVertical, paddingHorizontal: layout.compactRowPaddingHorizontal, borderRadius: radius.compact, borderWidth: 1, borderColor: colors.neutral.border, backgroundColor: colors.neutral.surface, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, unread: { backgroundColor: colors.neutral.backgroundRaised, borderColor: colors.avatarBorder, borderLeftWidth: 3, borderLeftColor: colors.brand.blue }, icon: { width: layout.standardIconSize, height: layout.standardIconSize, borderRadius: radius.medium, alignItems: 'center', justifyContent: 'center' }, categoryRow: { minHeight: 18, flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: spacing.xs }, unreadLabel: { paddingHorizontal: spacing.xs, borderRadius: radius.pill, backgroundColor: colors.brand.blueSoft } });
