import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { Image } from 'expo-image';
import { ScrollView, StyleSheet, View } from 'react-native';

import { AnimatedPressable } from '@/components/common/animated-pressable';
import { AppButton } from '@/components/common/app-button';
import { AppText } from '@/components/common/app-text';
import { AppTextInput } from '@/components/common/app-text-input';
import { EmptyState } from '@/components/states/content-state';
import { assessmentPeriods, coachAssessmentSkills, commentSuggestions, getRecommendedGoal, goalPresets, improvementOptions, ratingLabels, strengthOptions } from '@/data/assessments';
import { getLessonById } from '@/data/learning';
import { colors, layout, radius, shadows, spacing } from '@/design/tokens';
import { AcademyPlayer } from '@/types/academy';
import { AssessmentDevelopmentGoal, AssessmentDraft, AssessmentPeriod, AssessmentSkillKey, SkillRatingValue } from '@/types/assessment';

export function AssessmentPlayerSummary({ player, onChange }: { readonly player: AcademyPlayer; readonly onChange?: () => void }) {
  const initials = player.name.split(' ').map((part) => part[0]).slice(0, 2).join('');
  return <View style={styles.playerSummary}><View style={styles.avatar}><AppText weight="extraBold" color={colors.brand.navy}>{initials}</AppText></View><View style={styles.grow}><AppText variant="heading" weight="extraBold" numberOfLines={2}>{player.name}</AppText><AppText variant="caption" color={colors.neutral.textSecondary}>{player.playerId} · {player.category} · #{player.jerseyNumber}</AppText></View>{onChange ? <AnimatedPressable accessibilityRole="button" accessibilityLabel="Change selected player" onPress={onChange} style={styles.change}><AppText variant="caption" weight="extraBold" color={colors.brand.blue}>CHANGE</AppText></AnimatedPressable> : null}</View>;
}

export function PeriodSelector({ value, onChange }: { readonly value: AssessmentPeriod; readonly onChange: (value: AssessmentPeriod) => void }) {
  const labels: Readonly<Record<AssessmentPeriod, string>> = { 'Today’s Session': 'Session', 'Weekly Review': 'Weekly', 'Monthly Review': 'Monthly', 'Training Block': 'Block' };
  return <View accessibilityRole="radiogroup" accessibilityLabel="Assessment period" style={styles.period}>{assessmentPeriods.map((period) => { const active = value === period; return <AnimatedPressable key={period} accessibilityRole="radio" accessibilityLabel={`Assessment period ${period}`} accessibilityState={{ checked: active, selected: active }} onPress={() => onChange(period)} style={[styles.periodOption, active && styles.periodSelected]}><AppText variant="caption" weight="extraBold" color={active ? colors.neutral.white : colors.neutral.textSecondary}>{labels[period]}</AppText></AnimatedPressable>; })}</View>;
}

export function ChoiceChips<T extends string>({ values, selected, onSelect, labelPrefix }: { readonly values: readonly T[]; readonly selected: T; readonly onSelect: (value: T) => void; readonly labelPrefix: string }) {
  return <View style={styles.chips}>{values.map((value) => { const active = value === selected; return <AnimatedPressable key={value} accessibilityRole="radio" accessibilityLabel={`${labelPrefix}: ${value}`} accessibilityState={{ selected: active, checked: active }} onPress={() => onSelect(value)} style={[styles.chip, active && styles.chipSelected]}><AppText variant="bodySmall" weight="semibold" color={active ? colors.neutral.white : colors.neutral.textSecondary}>{value}</AppText></AnimatedPressable>; })}</View>;
}

export function SingleChoiceField({ title, values, selected, customValue, errorMessage, onSelect, onCustomChange }: { readonly title: string; readonly values: readonly string[]; readonly selected: string; readonly customValue: string; readonly errorMessage?: string; readonly onSelect: (value: string) => void; readonly onCustomChange: (value: string) => void }) {
  return <View style={styles.field}><AppText variant="heading" weight="extraBold">{title}</AppText><ChoiceChips values={values} selected={selected} onSelect={onSelect} labelPrefix={title} />{selected === 'Custom' ? <AppTextInput accessibilityLabel={`Custom ${title.toLowerCase()}`} value={customValue} onChangeText={onCustomChange} maxLength={48} placeholder={`Enter a custom ${title.toLowerCase()}`} returnKeyType="done" error={Boolean(errorMessage)} /> : null}{errorMessage ? <View accessibilityRole="alert"><AppText variant="caption" weight="semibold" color={colors.status.error}>{errorMessage}</AppText></View> : null}</View>;
}

export function SkillRatings({ values, previous, errorMessage, onChange, onSetAll, onCopyPrevious }: { readonly values: AssessmentDraft['skillRatings']; readonly previous?: AssessmentDraft['skillRatings']; readonly errorMessage?: string; readonly onChange: (skill: AssessmentSkillKey, rating: SkillRatingValue) => void; readonly onSetAll: () => void; readonly onCopyPrevious: () => void }) {
  return <View style={styles.skillSection}><View style={styles.quickRatingActions}><AppButton label="Set all to 3" variant="secondary" onPress={onSetAll} style={styles.flexButton} /><AppButton label="Copy Previous" variant="secondary" onPress={onCopyPrevious} disabled={!previous || !Object.keys(previous).length} style={styles.flexButton} /></View>{errorMessage ? <View accessibilityRole="alert"><AppText variant="caption" weight="semibold" color={colors.status.error}>{errorMessage}</AppText></View> : null}{coachAssessmentSkills.map((skill) => { const selected = values[skill.key]; return <View key={skill.key} style={styles.skillRow}><View style={styles.skillTop}><AppText variant="bodySmall" weight="bold">{skill.label}</AppText>{selected ? <AppText variant="caption" weight="bold" color={colors.brand.blue}>{ratingLabels[selected]}</AppText> : null}</View><View accessibilityRole="radiogroup" accessibilityLabel={`${skill.label} rating`} style={styles.ratingButtons}>{([1, 2, 3, 4, 5] as const).map((rating) => { const active = rating === selected; return <AnimatedPressable key={rating} accessibilityRole="radio" accessibilityLabel={`${skill.label}, ${rating}, ${ratingLabels[rating]}`} accessibilityState={{ checked: active, selected: active }} onPress={() => onChange(skill.key, rating)} style={[styles.ratingButton, active && styles.ratingSelected]}><AppText variant="bodySmall" weight="extraBold" color={active ? colors.neutral.white : colors.neutral.textSecondary}>{rating}</AppText></AnimatedPressable>; })}</View></View>; })}</View>;
}

export function CoachCommentField({ value, errorMessage, onChange }: { readonly value: string; readonly errorMessage?: string; readonly onChange: (value: string) => void }) {
  return <View style={styles.field}><AppText variant="heading" weight="extraBold">Coach comment</AppText><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.suggestions}>{commentSuggestions.slice(0, 3).map((suggestion) => <AnimatedPressable key={suggestion} accessibilityRole="button" accessibilityLabel={`Use comment: ${suggestion}`} onPress={() => onChange(suggestion)} style={styles.suggestion}><MaterialCommunityIcons name="lightning-bolt-outline" size={16} color={colors.brand.blue} /><AppText variant="caption" weight="semibold" color={colors.brand.navy} numberOfLines={2}>{suggestion}</AppText></AnimatedPressable>)}</ScrollView><AppTextInput accessibilityLabel="Coach comment" value={value} onChangeText={onChange} maxLength={240} multiline placeholder="Add a short, useful note for the player and parent." error={Boolean(errorMessage)} /><View style={styles.commentMeta}>{errorMessage ? <View accessibilityRole="alert" style={styles.grow}><AppText variant="caption" weight="semibold" color={colors.status.error}>{errorMessage}</AppText></View> : <View style={styles.grow} />}<AppText variant="caption" color={colors.neutral.textMuted}>{value.length} / 240</AppText></View></View>;
}

export function GoalSelector({ selected, improvementArea, onSelect }: { readonly selected?: AssessmentDevelopmentGoal; readonly improvementArea: string; readonly onSelect: (goal?: AssessmentDevelopmentGoal) => void }) {
  const recommended = selected ?? getRecommendedGoal(improvementArea);
  const active = selected?.title === recommended.title;
  const index = Math.max(0, goalPresets.findIndex((goal) => goal.title === recommended.title));
  const chooseAnother = () => onSelect(goalPresets[(index + 1) % goalPresets.length]);
  return <View style={styles.field}><View style={styles.sectionHeading}><AppText variant="heading" weight="extraBold">Recommended goal</AppText><AnimatedPressable accessibilityRole="button" accessibilityLabel="Choose another development goal" onPress={chooseAnother} style={styles.chooseAnother}><AppText variant="caption" weight="extraBold" color={colors.brand.blue}>CHOOSE ANOTHER</AppText></AnimatedPressable></View><AnimatedPressable accessibilityRole="checkbox" accessibilityLabel={recommended.title} accessibilityState={{ checked: active }} onPress={() => onSelect(active ? undefined : recommended)} style={[styles.goal, active && styles.goalSelected]}><MaterialCommunityIcons name={active ? 'check-circle' : 'target'} size={20} color={active ? colors.brand.blue : colors.neutral.textMuted} /><View style={styles.grow}><AppText variant="bodySmall" weight="bold">{recommended.title}</AppText><AppText variant="caption" color={colors.neutral.textSecondary}>{recommended.target} · {recommended.dueLabel}</AppText></View></AnimatedPressable></View>;
}

export function LessonRecommendations({ lessonIds, selectedIds, onToggle }: { readonly lessonIds: readonly string[]; readonly selectedIds: readonly string[]; readonly onToggle: (lessonId: string) => void }) {
  const lessons = lessonIds.flatMap((id) => { const lesson = getLessonById(id); return lesson ? [lesson] : []; });
  return <View style={styles.field}><View style={styles.sectionHeading}><AppText variant="heading" weight="extraBold">Recommend Academy Sessions</AppText><AppText variant="caption" color={colors.neutral.textSecondary}>{selectedIds.length} / 2 selected</AppText></View>{lessons.length ? <View style={styles.lessonList}>{lessons.map((lesson) => { const active = selectedIds.includes(lesson.id); const disabled = !active && selectedIds.length >= 2; return <AnimatedPressable key={lesson.id} accessibilityRole="checkbox" accessibilityLabel={`Recommend ${lesson.title}`} accessibilityState={{ checked: active, disabled }} disabled={disabled} onPress={() => onToggle(lesson.id)} style={[styles.lesson, active && styles.lessonSelected, disabled && styles.disabled]}><Image source={lesson.thumbnail} contentFit="cover" transition={160} style={styles.thumbnail} /><View style={styles.grow}><AppText variant="bodySmall" weight="extraBold" numberOfLines={2}>{lesson.title}</AppText><AppText variant="caption" color={colors.neutral.textSecondary}>{lesson.category} · {lesson.durationMinutes} min</AppText></View><MaterialCommunityIcons name={active ? 'checkbox-marked-circle' : 'checkbox-blank-circle-outline'} size={23} color={active ? colors.brand.blue : colors.neutral.textMuted} /></AnimatedPressable>; })}</View> : <EmptyState compact icon="book-open-variant" title="No matching Session" message="You can still save the feedback without a Session recommendation." />}</View>;
}

export const compactStrengthOptions = [...strengthOptions.slice(0, 6), 'Custom'] as const;
export const compactImprovementOptions = [...improvementOptions.slice(0, 6), 'Custom'] as const;

const styles = StyleSheet.create({
  grow: { flex: 1, minWidth: 0 }, field: { gap: spacing.sm }, sectionHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm },
  playerSummary: { ...shadows.card, minHeight: 76, padding: layout.cardPadding, borderWidth: 1, borderColor: colors.neutral.border, borderRadius: radius.standard, backgroundColor: colors.neutral.surface, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  avatar: { width: 48, height: 48, borderRadius: radius.pill, backgroundColor: colors.brand.blueSoft, alignItems: 'center', justifyContent: 'center' }, change: { minHeight: layout.minTouchTarget, paddingHorizontal: spacing.xs, alignItems: 'center', justifyContent: 'center' },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, chip: { minHeight: layout.chipHeight, paddingHorizontal: spacing.sm, borderWidth: 1, borderColor: colors.neutral.border, borderRadius: radius.pill, backgroundColor: colors.neutral.surface, alignItems: 'center', justifyContent: 'center' }, chipSelected: { borderColor: colors.brand.navy, backgroundColor: colors.brand.navy }, period: { minHeight: layout.chipHeight, padding: 3, borderRadius: radius.medium, backgroundColor: colors.neutral.backgroundRaised, flexDirection: 'row', gap: 3 }, periodOption: { flex: 1, minWidth: 0, borderRadius: radius.small, alignItems: 'center', justifyContent: 'center' }, periodSelected: { backgroundColor: colors.brand.navy },
  skillSection: { gap: spacing.sm }, quickRatingActions: { flexDirection: 'row', gap: layout.cardGap }, flexButton: { flex: 1, paddingHorizontal: spacing.xs }, skillRow: { padding: spacing.sm, borderWidth: 1, borderColor: colors.neutral.border, borderRadius: radius.medium, backgroundColor: colors.neutral.surface, gap: spacing.xs }, skillTop: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.xs }, ratingButtons: { flexDirection: 'row', gap: spacing.xs }, ratingButton: { flex: 1, height: layout.chipHeight, borderWidth: 1, borderColor: colors.neutral.borderStrong, borderRadius: radius.small, backgroundColor: colors.neutral.backgroundRaised, alignItems: 'center', justifyContent: 'center' }, ratingSelected: { borderColor: colors.brand.blue, backgroundColor: colors.brand.blue },
  suggestions: { gap: spacing.xs, paddingRight: spacing.md }, suggestion: { width: 188, minHeight: layout.chipHeight, paddingHorizontal: spacing.sm, borderRadius: radius.medium, backgroundColor: colors.brand.blueSoft, flexDirection: 'row', alignItems: 'center', gap: 4 }, commentMeta: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm },
  chooseAnother: { minHeight: layout.minTouchTarget, paddingLeft: spacing.xs, alignItems: 'flex-end', justifyContent: 'center' }, goal: { minHeight: 62, padding: spacing.sm, borderWidth: 1, borderColor: colors.neutral.border, borderRadius: radius.medium, backgroundColor: colors.neutral.surface, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, goalSelected: { borderColor: colors.brand.blue, backgroundColor: colors.brand.blueSoft },
  lessonList: { gap: layout.cardGap }, lesson: { minHeight: 76, padding: spacing.xs, borderWidth: 1, borderColor: colors.neutral.border, borderRadius: radius.medium, backgroundColor: colors.neutral.surface, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, lessonSelected: { borderColor: colors.brand.blue, backgroundColor: colors.brand.blueSoft }, thumbnail: { width: 88, height: 56, borderRadius: radius.small, backgroundColor: colors.neutral.backgroundRaised }, disabled: { opacity: 0.45 },
});
