import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { memo } from 'react';
import { ScrollView, StyleSheet, View } from 'react-native';

import { AnimatedPressable } from '@/components/common/animated-pressable';
import { AppButton } from '@/components/common/app-button';
import { AppText } from '@/components/common/app-text';
import { AppTextInput } from '@/components/common/app-text-input';
import { ProgressBar } from '@/components/common/progress-bar';
import { StatusBadge } from '@/components/common/status-badge';
import { EmptyState } from '@/components/states/content-state';
import { getAttendanceStatusLabel } from '@/data/attendance';
import { colors, layout, radius, shadows, spacing } from '@/design/tokens';
import { AcademyPlayer } from '@/types/academy';
import { AttendanceFilter, AttendanceSessionDefinition, AttendanceStatus, AttendanceSummary, PlayerAttendanceEntry, SessionAttendance } from '@/types/attendance';

const tones: Readonly<Record<AttendanceStatus, 'success' | 'error' | 'warning' | 'neutral'>> = { present: 'success', absent: 'error', late: 'warning', 'not-marked': 'neutral' };
const statusColors: Readonly<Record<AttendanceStatus, string>> = { present: colors.status.success, absent: colors.status.error, late: colors.status.warning, 'not-marked': colors.neutral.textSecondary };
const filters: readonly { value: AttendanceFilter; label: string }[] = [{ value: 'all', label: 'All' }, { value: 'not-marked', label: 'Not Marked' }, { value: 'present', label: 'Present' }, { value: 'absent', label: 'Absent' }, { value: 'late', label: 'Late' }];
const controls: readonly { status: Exclude<AttendanceStatus, 'not-marked'>; short: string }[] = [{ status: 'present', short: 'P' }, { status: 'absent', short: 'A' }, { status: 'late', short: 'L' }];

export function AttendanceSessionSelector({ sessions, selectedId, submittedIds, onSelect }: { readonly sessions: readonly AttendanceSessionDefinition[]; readonly selectedId: string; readonly submittedIds: ReadonlySet<string>; readonly onSelect: (sessionId: string) => void }) {
  return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.sessionList} accessibilityLabel="Training session selector">{sessions.map((session) => <AnimatedPressable key={session.id} testID={`attendance-session-${session.id}`} accessibilityRole="button" accessibilityLabel={`${session.displayDate}, ${session.timeLabel}, ${session.squadId.toUpperCase()}${submittedIds.has(session.id) ? ', submitted' : ''}`} accessibilityState={{ selected: selectedId === session.id }} onPress={() => onSelect(session.id)} style={[styles.sessionCard, selectedId === session.id && styles.sessionCardSelected]}><View style={styles.sessionTop}><AppText variant="caption" weight="extraBold" color={selectedId === session.id ? colors.neutral.white : colors.brand.blue}>{session.squadId.toUpperCase()}</AppText>{submittedIds.has(session.id) ? <MaterialCommunityIcons name="check-circle" size={17} color={selectedId === session.id ? colors.status.successSoft : colors.status.success} /> : null}</View><AppText variant="bodySmall" weight="extraBold" color={selectedId === session.id ? colors.neutral.white : colors.neutral.text}>{session.shortDate}</AppText><AppText variant="caption" color={selectedId === session.id ? colors.navyMutedText : colors.neutral.textSecondary}>{session.timeLabel}</AppText><AppText variant="caption" weight="bold" color={selectedId === session.id ? colors.brand.gold : colors.neutral.textMuted}>{session.timing === 'current' ? 'Current session' : session.timing === 'upcoming' ? 'Upcoming' : 'Recent'}</AppText></AnimatedPressable>)}</ScrollView>;
}

export function AttendanceSessionCard({ session, squadName, submitted }: { readonly session: AttendanceSessionDefinition; readonly squadName: string; readonly submitted: boolean }) {
  return <View style={styles.sessionDetail}><View style={styles.detailTop}><View style={styles.grow}><AppText variant="caption" weight="extraBold" color={colors.brand.blue}>SELECTED SESSION</AppText><AppText variant="title" weight="extraBold">{squadName}</AppText></View><StatusBadge label={submitted ? 'Submitted' : 'Draft'} tone={submitted ? 'success' : 'warning'} /></View><View style={styles.detailGrid}><Detail icon="calendar-outline" text={session.displayDate} /><Detail icon="clock-outline" text={session.timeLabel} /><Detail icon="map-marker-outline" text={session.ground} /><Detail icon="whistle-outline" text="Coach Sandeep" /></View><View style={styles.focus}><MaterialCommunityIcons name="target" size={19} color={colors.brand.blue} /><AppText variant="bodySmall" style={styles.grow}><AppText variant="bodySmall" weight="bold">Focus: </AppText>{session.focus}</AppText></View></View>;
}
function Detail({ icon, text }: { readonly icon: keyof typeof MaterialCommunityIcons.glyphMap; readonly text: string }) { return <View style={styles.detail}><MaterialCommunityIcons name={icon} size={17} color={colors.neutral.textSecondary} /><AppText variant="caption" color={colors.neutral.textSecondary} numberOfLines={2} style={styles.grow}>{text}</AppText></View>; }

export function AttendanceSummaryBar({ summary }: { readonly summary: AttendanceSummary }) {
  return <View accessibilityRole="summary" accessibilityLabel={`${summary.total} players. ${summary.present} present, ${summary.absent} absent, ${summary.late} late, ${summary.notMarked} not marked.`} style={styles.summary}><View style={styles.summaryTop}><AppText variant="heading" weight="extraBold">Attendance Summary</AppText><AppText variant="caption" weight="bold" color={colors.brand.blue}>{summary.marked} of {summary.total} marked</AppText></View><ProgressBar progress={summary.total ? summary.marked / summary.total : 0} accessibilityLabel={`${summary.marked} of ${summary.total} players marked`} /><View style={styles.metrics}><SummaryMetric label="Total" value={summary.total} color={colors.brand.navy} /><SummaryMetric label="Present" value={summary.present} color={colors.status.success} /><SummaryMetric label="Absent" value={summary.absent} color={colors.status.error} /><SummaryMetric label="Late" value={summary.late} color={colors.status.warning} /><SummaryMetric label="Not Marked" value={summary.notMarked} color={colors.neutral.textSecondary} /></View></View>;
}
function SummaryMetric({ label, value, color }: { readonly label: string; readonly value: number; readonly color: string }) { return <View style={styles.summaryMetric}><AppText variant="heading" weight="extraBold" color={color}>{value}</AppText><AppText variant="caption" color={colors.neutral.textSecondary} numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.85}>{label}</AppText></View>; }

export function AttendanceQuickActions({ onMarkAll, onReset }: { readonly onMarkAll: () => void; readonly onReset: () => void }) {
  return <View style={styles.quickActions}><AppButton testID="attendance-mark-all" label="Mark all present" onPress={onMarkAll} accessibilityLabel="Mark all players present" style={styles.primaryAction} /><AppButton testID="attendance-reset" label="Reset" variant="secondary" onPress={onReset} accessibilityLabel="Reset all attendance statuses" style={styles.resetAction} /></View>;
}

export function AttendanceSearchAndFilter({ query, onQueryChange, selected, onSelect }: { readonly query: string; readonly onQueryChange: (value: string) => void; readonly selected: AttendanceFilter; readonly onSelect: (filter: AttendanceFilter) => void }) {
  return <View style={styles.filterBlock}><AppTextInput testID="attendance-search" accessibilityLabel="Search attendance roster by name, player ID, or jersey" value={query} onChangeText={onQueryChange} placeholder="Search player, ID or jersey" autoCapitalize="none" autoCorrect={false} returnKeyType="search" leading={<MaterialCommunityIcons name="magnify" size={layout.iconSizeStandard} color={colors.neutral.textSecondary} />} trailing={query ? <AnimatedPressable testID="attendance-search-clear" accessibilityRole="button" accessibilityLabel="Clear attendance search" onPress={() => onQueryChange('')} style={styles.clear}><MaterialCommunityIcons name="close-circle" size={layout.iconSizeCompact} color={colors.neutral.textSecondary} /></AnimatedPressable> : null} /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filterList} accessibilityRole="tablist">{filters.map((filter) => <AnimatedPressable key={filter.value} testID={`attendance-filter-${filter.value}`} accessibilityRole="tab" accessibilityState={{ selected: selected === filter.value }} accessibilityLabel={`${filter.label} attendance filter`} onPress={() => onSelect(filter.value)} style={[styles.filterChip, selected === filter.value && styles.filterChipSelected]}><AppText variant="caption" weight="bold" color={selected === filter.value ? colors.neutral.white : colors.neutral.textSecondary} numberOfLines={1}>{filter.label}</AppText></AnimatedPressable>)}</ScrollView></View>;
}

function AttendanceRowComponent({ player, entry, focused, disabled = false, onStatus, onNote }: { readonly player: AcademyPlayer; readonly entry: PlayerAttendanceEntry; readonly focused: boolean; readonly disabled?: boolean; readonly onStatus: (playerId: string, status: AttendanceStatus) => void; readonly onNote: (entry: PlayerAttendanceEntry, player: AcademyPlayer) => void }) {
  const initials = player.name.split(' ').map((part) => part[0]).slice(0, 2).join('');
  const canNote = entry.status === 'absent' || entry.status === 'late';
  return <View testID={`attendance-player-${player.id}`} style={[styles.rowCard, focused && styles.rowFocused, disabled && styles.rowDisabled]}><View accessible accessibilityLabel={`${player.name}, jersey ${player.jerseyNumber}, ${player.position}, currently ${getAttendanceStatusLabel(entry.status)}${entry.note ? `, note ${entry.note}` : ''}`} style={styles.playerLine}><View style={styles.avatar}><AppText variant="bodySmall" weight="extraBold" color={colors.brand.navy}>{initials}</AppText><View style={styles.jersey}><AppText variant="caption" weight="extraBold" color={colors.neutral.white}>{player.jerseyNumber}</AppText></View></View><View style={styles.grow}><AppText variant="bodySmall" weight="extraBold" numberOfLines={2}>{player.name}</AppText><AppText variant="caption" color={colors.neutral.textSecondary}>#{player.jerseyNumber} · {player.position}</AppText>{entry.note ? <AppText variant="caption" color={colors.neutral.textSecondary} numberOfLines={1}>Note: {entry.note}</AppText> : null}</View><View style={styles.statusColumn}><StatusBadge label={getAttendanceStatusLabel(entry.status)} tone={tones[entry.status]} />{canNote && !disabled ? <AnimatedPressable testID={`attendance-note-${player.id}`} accessibilityRole="button" accessibilityLabel={`${entry.note ? 'Edit' : 'Add'} attendance note for ${player.name}`} onPress={() => onNote(entry, player)} style={styles.noteButton}><MaterialCommunityIcons name={entry.note ? 'note-edit-outline' : 'dots-horizontal'} size={19} color={colors.brand.blue} /><AppText variant="caption" weight="bold" color={colors.brand.blue}>{entry.note ? 'Edit' : 'Note'}</AppText></AnimatedPressable> : null}</View></View><View style={styles.segment}>{controls.map((control) => { const selected = entry.status === control.status; return <AnimatedPressable key={control.status} testID={`attendance-${player.id}-${control.status}`} accessibilityRole="button" accessibilityLabel={`${selected ? 'Clear' : 'Mark'} ${player.name} ${getAttendanceStatusLabel(control.status)}`} accessibilityHint={selected ? 'Tap again to clear this status' : undefined} accessibilityState={{ selected, disabled }} disabled={disabled} onPress={() => onStatus(player.id, control.status)} style={[styles.segmentButton, selected && { backgroundColor: statusColors[control.status], borderColor: statusColors[control.status] }]}><AppText variant="bodySmall" weight="extraBold" color={selected ? colors.neutral.white : statusColors[control.status]}>{control.short}</AppText><AppText variant="caption" weight="bold" color={selected ? colors.neutral.white : colors.neutral.textSecondary} numberOfLines={1}>{getAttendanceStatusLabel(control.status)}</AppText></AnimatedPressable>; })}</View></View>;
}
export const AttendanceRow = memo(AttendanceRowComponent);

export function AttendanceHistory({ records, sessions, onOpen }: { readonly records: readonly SessionAttendance[]; readonly sessions: readonly AttendanceSessionDefinition[]; readonly onOpen: (sessionId: string) => void }) {
  const history = [...records].sort((a, b) => b.date.localeCompare(a.date));
  return <View style={styles.history}><AppText variant="heading" weight="extraBold">Recent Attendance</AppText>{history.length ? history.map((record) => { const session = sessions.find((item) => item.id === record.sessionId); if (!session) return null; const summary = { present: record.entries.filter((entry) => entry.status === 'present').length, absent: record.entries.filter((entry) => entry.status === 'absent').length, late: record.entries.filter((entry) => entry.status === 'late').length, marked: record.entries.filter((entry) => entry.status !== 'not-marked').length }; return <AnimatedPressable key={record.sessionId} accessibilityRole="button" accessibilityLabel={`Open ${session.displayDate} attendance, ${summary.marked} marked`} onPress={() => onOpen(record.sessionId)} style={styles.historyRow}><View style={styles.historyIcon}><MaterialCommunityIcons name="clipboard-check-outline" size={21} color={colors.status.success} /></View><View style={styles.grow}><AppText variant="bodySmall" weight="extraBold">{session.squadId.toUpperCase()} · {session.displayDate}</AppText><AppText variant="caption" color={colors.neutral.textSecondary}>{summary.marked} marked · {summary.present} present · {summary.absent} absent · {summary.late} late</AppText><AppText variant="caption" color={colors.neutral.textMuted}>Coach Sandeep · {record.savedAt ? new Date(record.savedAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }) : 'Submitted'}</AppText></View><StatusBadge label="Submitted" tone="success" /><MaterialCommunityIcons name="chevron-right" size={21} color={colors.brand.blue} /></AnimatedPressable>; }) : <EmptyState compact icon="calendar-blank-outline" title="No attendance yet" message="Saved squad sessions will appear here." />}</View>;
}

const styles = StyleSheet.create({
  sessionList: { gap: spacing.xs, paddingRight: layout.pageHorizontal }, sessionCard: { width: 138, minHeight: 104, padding: spacing.sm, borderWidth: 1, borderColor: colors.neutral.border, borderRadius: radius.standard, backgroundColor: colors.neutral.surface, gap: 3 }, sessionCardSelected: { backgroundColor: colors.brand.navy, borderColor: colors.brand.navy }, sessionTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  sessionDetail: { ...shadows.card, padding: layout.cardPadding, borderWidth: 1, borderColor: colors.neutral.border, borderRadius: radius.standard, backgroundColor: colors.neutral.surface, gap: spacing.sm }, detailTop: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm }, detailGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, detail: { width: '48%', minWidth: 0, flexGrow: 1, flexDirection: 'row', alignItems: 'flex-start', gap: 5 }, focus: { padding: spacing.sm, borderRadius: radius.medium, backgroundColor: colors.brand.blueSoft, flexDirection: 'row', alignItems: 'center', gap: spacing.xs }, grow: { flex: 1, minWidth: 0 },
  summary: { ...shadows.card, padding: layout.cardPadding, borderWidth: 1, borderColor: colors.neutral.border, borderRadius: radius.standard, backgroundColor: colors.neutral.surface, gap: spacing.sm }, summaryTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm }, metrics: { flexDirection: 'row' }, summaryMetric: { flex: 1, minWidth: 0, alignItems: 'center', gap: 2 },
  quickActions: { flexDirection: 'row', gap: spacing.xs }, primaryAction: { flex: 1 }, resetAction: { minWidth: 88, paddingHorizontal: spacing.sm },
  filterBlock: { gap: spacing.xs }, clear: { width: layout.minTouchTarget, height: layout.minTouchTarget, marginRight: -spacing.md, alignItems: 'center', justifyContent: 'center' }, filterList: { gap: spacing.xs, paddingRight: layout.pageHorizontal }, filterChip: { minHeight: layout.chipHeight, paddingHorizontal: spacing.sm, borderWidth: 1, borderColor: colors.neutral.border, borderRadius: radius.pill, backgroundColor: colors.neutral.surface, alignItems: 'center', justifyContent: 'center' }, filterChipSelected: { backgroundColor: colors.brand.navy, borderColor: colors.brand.navy }, pressed: { opacity: 0.75 },
  rowCard: { ...shadows.card, minHeight: 104, paddingHorizontal: layout.compactRowPaddingHorizontal, paddingVertical: layout.compactRowPaddingVertical, borderWidth: 1, borderColor: colors.neutral.border, borderRadius: radius.compact, backgroundColor: colors.neutral.surface, gap: spacing.xs }, rowFocused: { borderWidth: 2, borderColor: colors.brand.blue, backgroundColor: colors.brand.blueSoft }, rowDisabled: { backgroundColor: colors.neutral.backgroundRaised }, playerLine: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, avatar: { width: 40, height: 40, borderRadius: radius.pill, backgroundColor: colors.brand.blueSoft, borderWidth: 1, borderColor: colors.avatarBorder, alignItems: 'center', justifyContent: 'center' }, jersey: { position: 'absolute', right: -3, bottom: -3, minWidth: 20, height: 20, paddingHorizontal: 3, borderRadius: radius.pill, backgroundColor: colors.brand.navy, borderWidth: 2, borderColor: colors.neutral.surface, alignItems: 'center', justifyContent: 'center' }, statusColumn: { minWidth: 72, alignItems: 'flex-end', gap: 2 }, noteButton: { minHeight: layout.chipHeight, paddingHorizontal: spacing.xs, flexDirection: 'row', alignItems: 'center', gap: 2 }, segment: { minHeight: layout.chipHeight, flexDirection: 'row', gap: 5 }, segmentButton: { flex: 1, minWidth: 0, minHeight: layout.chipHeight, borderWidth: 1, borderColor: colors.neutral.borderStrong, borderRadius: radius.small, backgroundColor: colors.neutral.backgroundRaised, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 3 },
  history: { gap: layout.cardGap }, historyRow: { ...shadows.card, minHeight: 78, padding: layout.compactRowPaddingHorizontal, borderWidth: 1, borderColor: colors.neutral.border, borderRadius: radius.compact, backgroundColor: colors.neutral.surface, flexDirection: 'row', alignItems: 'center', gap: spacing.xs }, historyIcon: { width: layout.compactIconSize, height: layout.compactIconSize, borderRadius: radius.small, backgroundColor: colors.status.successSoft, alignItems: 'center', justifyContent: 'center' },
});
