import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { StyleSheet, View } from 'react-native';

import { AnimatedPressable } from '@/components/common/animated-pressable';
import { AppButton } from '@/components/common/app-button';
import { AppText } from '@/components/common/app-text';
import { BrandLogo } from '@/components/common/brand-logo';
import { ProgressBar } from '@/components/common/progress-bar';
import { colors, layout, motion, radius, shadows, spacing } from '@/design/tokens';
import { AcademyPlayer, CoachPlayerAction, SharedSkillAssessment } from '@/types/academy';
import { LearningLesson } from '@/types/learning';

export function CoachPlayerIdentityCard({ player }: { readonly player: AcademyPlayer }) {
  const initials = player.name.split(' ').map((part) => part[0]).slice(0, 2).join('');
  return <View accessibilityLabel={`${player.name}, ${player.playerId}, jersey ${player.jerseyNumber}, ${player.category}, ${player.position}, ${player.dominantFoot} foot, membership ${player.membershipStatus}`} style={styles.identity}><View style={styles.identityTop}><View style={styles.avatar}><AppText variant="title" weight="extraBold" color={colors.neutral.white}>{initials}</AppText><View style={styles.jersey}><AppText variant="caption" weight="extraBold" color={colors.brand.navy}>{player.jerseyNumber}</AppText></View></View><View style={styles.grow}><AppText variant="title" weight="extraBold" color={colors.neutral.white}>{player.name}</AppText><AppText variant="caption" color={colors.navyMutedText}>{player.playerId}</AppText><AppText variant="bodySmall" weight="semibold" color={colors.neutral.white}>{player.category} · {player.position}</AppText></View><BrandLogo containerSize={48} feature /></View><View style={styles.identityMeta}><IdentityMeta label="Dominant foot" value={player.dominantFoot} /><IdentityMeta label="Age" value={String(player.age)} /><IdentityMeta label="Membership" value={player.membershipStatus === 'active' ? 'Active' : 'Pending renewal'} /></View></View>;
}
function IdentityMeta({ label, value }: { readonly label: string; readonly value: string }) { return <View style={styles.identityMetaItem}><AppText variant="caption" color={colors.navyMutedText}>{label}</AppText><AppText variant="bodySmall" weight="bold" color={colors.neutral.white}>{value}</AppText></View>; }

const actionDefinitions: readonly { action: CoachPlayerAction | 'attendance'; label: string; icon: keyof typeof MaterialCommunityIcons.glyphMap }[] = [{ action: 'attendance', label: 'Attendance', icon: 'clipboard-check-outline' }, { action: 'feedback', label: 'Feedback', icon: 'message-draw' }, { action: 'progress', label: 'Progress', icon: 'chart-line' }];
export function PlayerQuickActions({ onAction }: { readonly onAction: (action: CoachPlayerAction | 'attendance') => void }) { return <View style={styles.actionGrid}>{actionDefinitions.map((item) => <AnimatedPressable key={item.action} testID={`coach-player-action-${item.action}`} accessibilityRole="button" accessibilityLabel={item.label} onPress={() => onAction(item.action)} pressedScale={motion.scale.pressStrong} style={styles.action}><View style={styles.actionIcon}><MaterialCommunityIcons name={item.icon} size={23} color={colors.brand.navy} /></View><AppText variant="bodySmall" weight="bold" numberOfLines={1}>{item.label}</AppText></AnimatedPressable>)}</View>; }

export function PlayerSnapshotCard({ player, assessment, onAttendance, onProgress }: { readonly player: AcademyPlayer; readonly assessment?: SharedSkillAssessment; readonly onAttendance: () => void; readonly onProgress: () => void }) {
  return <View style={styles.card} accessibilityLabel={`Current snapshot. Attendance ${player.attendance.percentage} percent. Coach rating ${player.latestRating.toFixed(1)} out of 5. Focus ${player.focus}.`}><View style={styles.snapshot}><SnapshotMetric label="Attendance" value={`${player.attendance.percentage}%`} color={colors.status.success} /><SnapshotMetric label="Coach rating" value={`${player.latestRating.toFixed(1)} / 5`} color={colors.brand.navy} /><SnapshotMetric label="Current focus" value={player.focus} color={colors.brand.blue} compact /></View><View style={styles.snapshotActions}><AppButton label="Attendance history" variant="secondary" onPress={onAttendance} style={styles.snapshotAction} /><AppButton label={assessment ? 'Full progress' : 'Add assessment'} variant="secondary" onPress={onProgress} style={styles.snapshotAction} /></View></View>;
}
function SnapshotMetric({ label, value, color, compact = false }: { readonly label: string; readonly value: string; readonly color: string; readonly compact?: boolean }) { return <View style={styles.snapshotMetric}><AppText variant="caption" color={colors.neutral.textSecondary}>{label}</AppText><AppText variant={compact ? 'bodySmall' : 'heading'} weight="extraBold" color={color} numberOfLines={2}>{value}</AppText></View>; }

export function PlayerGoalCard({ player, lesson, onOpenLesson }: { readonly player: AcademyPlayer; readonly lesson?: LearningLesson; readonly onOpenLesson?: () => void }) {
  return <View style={styles.goal}><View style={styles.sectionTop}><View style={styles.grow}><AppText variant="caption" weight="extraBold" color={colors.brand.blue}>CURRENT GOAL</AppText><AppText variant="title" weight="extraBold">{player.focus}</AppText></View><AppText variant="title" weight="extraBold" color={colors.brand.blue}>{player.goalProgress}%</AppText></View><AppText variant="bodySmall" weight="semibold">Target: {player.goalTarget}</AppText><ProgressBar progress={player.goalProgress / 100} accessibilityLabel={`${player.focus} goal, ${player.goalProgress} percent complete`} /><View style={styles.note}><MaterialCommunityIcons name="whistle-outline" size={19} color={colors.brand.blue} /><AppText variant="bodySmall" color={colors.neutral.textSecondary} style={styles.grow}>{player.coachNote}</AppText></View>{lesson ? <View style={styles.lessonLine}><View style={styles.actionIcon}><MaterialCommunityIcons name="school-outline" size={21} color={colors.brand.navy} /></View><View style={styles.grow}><AppText variant="caption" color={colors.neutral.textSecondary}>ASSIGNED SESSION</AppText><AppText variant="bodySmall" weight="bold">{lesson.title}</AppText></View><AppButton label="Open" variant="secondary" onPress={onOpenLesson} /></View> : null}</View>;
}
const styles = StyleSheet.create({
  identity: { ...shadows.hero, padding: layout.cardPadding, borderRadius: radius.hero, backgroundColor: colors.brand.navy, gap: spacing.sm }, identityTop: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, avatar: { width: 54, height: 54, borderRadius: radius.pill, borderWidth: 2, borderColor: colors.brand.blue, backgroundColor: colors.brand.navySoft, alignItems: 'center', justifyContent: 'center' }, jersey: { position: 'absolute', right: -3, bottom: -3, minWidth: 23, height: 23, paddingHorizontal: 4, borderRadius: radius.pill, backgroundColor: colors.neutral.white, alignItems: 'center', justifyContent: 'center' }, grow: { flex: 1, minWidth: 0 }, identityMeta: { flexDirection: 'row', padding: spacing.xs, borderRadius: radius.medium, backgroundColor: colors.heroMetadata }, identityMetaItem: { flex: 1, minWidth: 0 },
  actionGrid: { flexDirection: 'row', gap: layout.cardGap }, action: { ...shadows.card, flex: 1, minWidth: 0, minHeight: 64, padding: spacing.xs, borderWidth: 1, borderColor: colors.neutral.border, borderRadius: radius.standard, backgroundColor: colors.neutral.surface, alignItems: 'center', justifyContent: 'center', gap: 4 }, actionIcon: { width: layout.standardIconSize, height: layout.standardIconSize, borderRadius: radius.small, backgroundColor: colors.brand.blueSoft, alignItems: 'center', justifyContent: 'center' },
  card: { ...shadows.card, padding: layout.cardPadding, borderWidth: 1, borderColor: colors.neutral.border, borderRadius: radius.standard, backgroundColor: colors.neutral.surface, gap: spacing.sm }, sectionTop: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: spacing.sm },
  snapshot: { flexDirection: 'row' }, snapshotMetric: { flex: 1, minWidth: 0, paddingHorizontal: spacing.xs, borderRightWidth: StyleSheet.hairlineWidth, borderRightColor: colors.neutral.divider, gap: 2 }, snapshotActions: { flexDirection: 'row', gap: spacing.xs }, snapshotAction: { flex: 1, paddingHorizontal: spacing.xs },
  goal: { ...shadows.card, padding: layout.largeCardPadding, borderWidth: 1, borderColor: colors.avatarBorder, borderRadius: radius.standard, backgroundColor: colors.brand.blueSoft, gap: spacing.sm }, note: { padding: spacing.sm, borderRadius: radius.medium, backgroundColor: colors.neutral.surface, flexDirection: 'row', alignItems: 'center', gap: spacing.xs }, lessonLine: { minHeight: 54, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
});
