export const layout = {
  pageHorizontal: 16,
  screenPadding: 16,
  compactScreenPadding: 16,
  contentMaxWidth: 600,
  minTouchTarget: 48,
  headerActionSize: 46,
  buttonHeight: 48,
  inputHeight: 48,
  multilineInputMinHeight: 96,
  chipHeight: 44,
  tabBarContentHeight: 64,
  tabBarHorizontalPadding: 8,
  tabBarPillHeight: 44,
  tabBarIconSize: 23,
  tabBarActiveIconSize: 21,
  tabBarLabelGap: 5,
  heroHeightRatio: 0.88,
  heroMinHeight: 332,
  heroMaxHeight: 356,
  heroButtonHeight: 48,
  heroActionIconSize: 34,
  pageTop: 14,
  headerToFirstSection: 20,
  sectionGap: 22,
  sectionHeaderToCard: 10,
  cardGap: 10,
  cardPadding: 15,
  standardCardPadding: 15,
  largeCardPadding: 18,
  visualCardPadding: 18,
  compactRowPadding: 12,
  compactRowPaddingVertical: 12,
  compactRowPaddingHorizontal: 14,
  compactRowMinHeight: 52,
  informationRowMinHeight: 44,
  learningImageAspectRatio: 2.15,
  tabClearance: 20,
  profileAvatarSize: 68,
  academyLogoSize: 48,
  brandLogoScale: 0.83,
  brandLogoVisualScale: 1.25,
  brandFeatureLogoSize: 84,
  menuIconSize: 40,
  rowIconSize: 40,
  compactIconSize: 36,
  standardIconSize: 40,
  dialogIconSize: 52,
  dialogMaxWidth: 420,
  selectRowMinHeight: 64,
  iconSizeCompact: 20,
  iconSizeStandard: 22,
  iconSizeFeature: 24,
} as const;

export const coachLayout = {
  pageHorizontal: layout.pageHorizontal,
  pageTop: layout.pageTop,
  headerToFirstSection: layout.headerToFirstSection,
  sectionGap: layout.sectionGap,
  sectionHeaderToCard: layout.sectionHeaderToCard,
  cardGap: layout.cardGap,
  cardPadding: layout.cardPadding,
  compactRowPaddingVertical: layout.compactRowPaddingVertical,
  compactRowPaddingHorizontal: layout.compactRowPaddingHorizontal,
  actionGridGap: layout.cardGap,
} as const;

export const coachTabBarMetrics = {
  height: 64,
  horizontalInset: 12,
  bottomInset: 10,
  activePillHeight: 44,
  activePillWidths: {
    index: 122,
    players: 106,
    attendance: 128,
    training: 112,
    profile: 102,
  },
  pillReferenceContentWidth: 416,
  minimumPillWidth: 92,
  inactiveIconGap: 6,
  contentClearance: 20,
  stickyActionHeight: 68,
  attendanceStickyActionHeight: 84,
  stickyContentClearance: 24,
} as const;
